### PR TITLE
Add color variables and styles from fluxboard and base-styles

### PR DESCRIPTION
**Pull request by allison-strandberg**
A step towards consolidating styles shared by Mapdwell applications in one source of truth. Adds the intense-orange color from app/styles/_base.scss in fluxboard and all colors from variables/_colors.scss and variables/_tachyons_variable_overrides.scss.

### CODE REVIEW

**Comment by allison-strandberg** [comment]
@dnix, I was wondering with @waissbluth about how we should approach the division of responsibility between mapdwell/tachyons-sass and base-styles.

One option is to move everything from base-styles into mapdwell/tachyons-sass and get rid of base-styles: advantages are that there's a single source of truth for styles and there are fewer pieces of the developer workflow.

Another option is to edit mapdwell/tachyons-sass only for overrides, like changing the tachyons default color blue, and keep new shared styles in base-styles. This way makes it easier to merge in main tachyons-sass changes.

This PR is from the "move everything to mapdwell/tachyons-sass" perspective, so if we want to keep base-styles I'll remove non-tachyons colors before merging.

Does one of these sound more appealing?

**Comment by dnix** [comment]
> @dnix, I was wondering with @waissbluth about how we should approach the division of responsibility between mapdwell/tachyons-sass and base-styles.
> 
> One option is to move everything from base-styles into mapdwell/tachyons-sass and get rid of base-styles: advantages are that there's a single source of truth for styles and there are fewer pieces of the developer workflow.
> 
> Another option is to edit mapdwell/tachyons-sass only for overrides, like changing the tachyons default color blue, and keep new shared styles in base-styles. This way makes it easier to merge in main tachyons-sass changes.
> 
> This PR is from the "move everything to mapdwell/tachyons-sass" perspective, so if we want to keep base-styles I'll remove non-tachyons colors before merging.
> 
> Does one of these sound more appealing?

i guess i lean toward the overrides-only mapdwell-tachyons, maintaining the narrow tachyons scope and not exposing app-specific styles in a public repo, which just feels a bit weird to me. but i don't feel that strongly if it is causing dev friction.

**Comment by allison-strandberg** [comment]
Ok, I'll edit this PR to only override existing tachyons colors, and add new colors (like the monthly chart's intense-orange) to base-styles instead.

**Comment by dnix** [comment]
just realized we never merged this, everything ready here? @allison-strandberg

**Review by waissbluth — APPROVED** [review]

**Review by dnix — APPROVED** [review]

**Comment by allison-strandberg** [comment]
Not ready yet, so I've converted the PR to a draft.

**Pull request merged**
